name: Test and package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install lua dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install luarocks
          sudo luarocks install luaunit
          sudo luarocks install luacov
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck addon --no-self -g

      - name: Run tests
        working-directory: ./tests
        run: lua -lluacov test_TrackingApi.lua

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build:
    runs-on: ubuntu-latest

    needs:
      - test

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.0.9

      - uses: actions/upload-artifact@v3
        with:
          name: TrackingMenu
          path: .release
